name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Bun (no Node lockfile required)
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: Set base path for project pages
        # username.github.io/repo -> /repo ; root site -> ''
        run: |
          if [ "${{ github.event.repository.name }}" != "${{ github.repository_owner }}.github.io" ]; then
            echo "BASE_PATH=/${{ github.event.repository.name }}" >> $GITHUB_ENV
          else
            echo "BASE_PATH=" >> $GITHUB_ENV
          fi

      - name: Build
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
